<?php
echo "<h1>Welcome SeaHeroQuest Scientist!<h1>";
echo "<br>Please sign the below AGB:<br>";
echo getenv("GREETINGS");
echo "<br>";

echo "Container Name: ";
echo gethostname();
echo "<br>";
echo "Client IP: ";
echo $_SERVER["REMOTE_ADDR"];

echo " ";
echo "<center>Agreement on the use of Data</center>";
echo "<center>collected by</center>";
echo "<center>the Sea Hero Quest App</center>";
echo " ";
echo " ";
echo "1.";
echo "Deutsche Telekom AG (“Telekom”) has developed a game application called Sea Hero";
echo "Quest (the Game). The Game has been carefully designed to answer a number of";
echo "key research questions related to how people navigate. The data set generated by";
echo "Deutsche Telekom’s Sea Hero Quest has led to the creation of the first global ";
echo "benchmark for human spatial navigation.";
echo " ";
echo " ";
?>
