<?php
echo "<h1>Welcome SeaHeroQuest Scientist!<h1>";
echo "<br>Please sign the below AGB:<br>";
echo getenv("GREETINGS");
echo "<br>";

echo "Container Name: ";
echo gethostname();
echo "<br>";
echo "Client IP: ";
echo $_SERVER["REMOTE_ADDR"];

echo "";
echo "<center>Agreement on the use of Data</center>";
echo "<center>collected by</center>";
echo "<center>the Sea Hero Quest App</center>";
echo "";
echo "";
echo "1.";
echo "Deutsche Telekom AG (“Telekom”) has developed a game application called “Sea Hero";
echo "Quest”(the "Game"). The Game has been carefully designed to answer a number of";
echo "key research questions related to how people navigate. The data set generated by";
echo "Deutsche Telekom’s ‘Sea Hero Quest’ has led to the creation of the first global ";
echo "benchmark for human spatial navigation. ";
echo "";
echo "";

echo "2.";
echo "Telekom will make the Data available to";
echo "scientists for the use in the course of dementia research projects and grants";
echo "the scientists an non-exclusive right to use the Data. The scientist are not";
echo "allowed to make the Data available to third parties outside of their research";
echo "project, unless Telekom has expressly agreed thereto or such transfer of the";
echo "Data is necessary in order to carry out their research project. In case of the";
echo "latter, the scientists has to inform Telekom in advance. ";
echo "";
echo "";

echo "3.";
echo "Telekom will make the Data available in an";
echo "anonymized form according to German data privacy law.";
echo "";
echo "";

echo "4.";
echo "The scientist hereby undertakes to use the Data only as permitted in this Agreement and in";
echo "compliance with all applicable local and international laws, rules,";
echo "regulations, orders and guidelines.";
echo "";
echo "";

echo "5.";      
echo "The Data are provided “as is” and Telekom makes";
echo "no representations and extend nor warranties of any kind, either expressed or";
echo "implied. There are no express or implied warranties of merchantability or fitness";
echo "for a particular purpose.";
echo "";
echo "";
 
echo "";
echo "6.";      
echo "All publications of the Data by the scientists";
echo "will acknowledge the contribution of Deutsche Telekom. The scientists agrees to";
echo "integrate the following wording in all Publications: “The data for this";
echo "research was generated by the Sea Hero Quest App – a Deutsche Telekom initiative.”";
echo "";

?>
