<?php
echo "<h1>Welcome SeaHeroQuest Scientist!<h1>";
echo "Please sign the below AGB:";
echo getenv("GREETINGS");
echo "<br>";

echo "Container Name: ";
echo gethostname();
echo "<br>";
echo "Client IP: ";
echo $_SERVER["REMOTE_ADDR"];
echo "

Agreement
on the use of Data



collected
by 



the
Sea Hero Quest App



 



1.           
Deutsche Telekom AG (“Telekom”) has developed a
game application called “Sea Hero Quest” (the “Game”). The Game has been
carefully designed to answer a number of key research questions related to how
people navigate. The data set generated
by Deutsche Telekom’s ‘Sea Hero Quest’ has led to the creation of the first
global benchmark for human spatial navigation. 



2.           
Telekom will make the Data available to
scientists for the use in the course of dementia research projects and grants
the scientists an non-exclusive right to use the Data. The scientist are not
allowed to make the Data available to third parties outside of their research
project, unless Telekom has expressly agreed thereto or such transfer of the
Data is necessary in order to carry out their research project. In case of the
latter, the scientists has to inform Telekom in advance. 



3.           
Telekom will make the Data available in an
anonymized form according to German data privacy law.



4.           
The scientist hereby undertakes to use the Data only as permitted in this Agreement and in
compliance with all applicable local and international laws, rules,
regulations, orders and guidelines.



5.           
The Data are provided “as is” and Telekom makes
no representations and extend nor warranties of any kind, either expressed or
implied. There are no express or implied warranties of merchantability or fitness
for a particular purpose.



6.           
All publications of the Data by the scientists
will acknowledge the contribution of Deutsche Telekom. The scientists agrees to
integrate the following wording in all Publications: “The data for this
research was generated by the Sea Hero Quest App – a Deutsche Telekom initiative.”





 



 



_________________________                                                _________________________



Place, Date                                                                                       Place,
Date



 



Deutsche Telekom AG                                                                 [Scientist]



by ________________________                                            by
_________________________



Name:                                                                                                Name:



Title:                                                                                                    Title:
"



?>
